version: '2'

services:
  auto-tests:
    container_name: "automated-test"
    build:
      context: .
    environment:
      BASE_URL: https://qauto.forstudy.space
      API_URL: https://qauto.forstudy.space/api
      HTTP_CREDENTIALS_USERNAME: ${HTTP_CREDENTIALS_USERNAME}
      HTTP_CREDENTIALS_PASSWORD: ${HTTP_CREDENTIALS_PASSWORD}
    volumes:
      - ./docker-playwright-report:/aqa-playwright/playwright-report