version: '2'

services:
  auto-tests:
    container_name: "automated-test"
    build:
      context: .
      args:
        BASE_URL: ${BASE_URL}
        API_URL: ${API_URL}
        HTTP_CREDENTIALS_USERNAME: ${HTTP_CREDENTIALS_USERNAME}
        HTTP_CREDENTIALS_PASSWORD: ${HTTP_CREDENTIALS_PASSWORD}
